'use client';

import { useState } from 'react';
import { Recommendation } from '@/types/recommendation';
import Link from 'next/link';
import { platformSourceLabel } from '@/lib/recommendationSources';
import {
  getRecommendationApplyHref,
  isExternalRecommendationHref,
} from '@/lib/recommendationApplyUrl';
import PlatformSourceIcon from '@/components/branding/PlatformSourceIcon';

const mosaicModuleLabel: Record<string, string> = {
  budget_orchestration: 'Budget',
  bid_policy: 'Bid',
  audience_strategy: 'Audience',
  placement: 'Placement',
  geo_daypart: 'Geo/Daypart',
};

interface PlatformSpecificPanelProps {
  recommendations: Recommendation[];
  /** Collapsed by default on MOSAIC / All tabs when user should focus on MOSAIC first */
  defaultCollapsed?: boolean;
}

function PlatformRecRow({ rec }: { rec: Recommendation }) {
  const categoryLabel = rec.nativeTypeLabel ?? mosaicModuleLabel[rec.type] ?? rec.type;
  const isNativeOnly = Boolean(rec.nativeTypeLabel);
  const href = getRecommendationApplyHref(rec);
  const external = isExternalRecommendationHref(href);

  const inner = (
  <>
      <div className="mb-1 flex flex-wrap items-center gap-2">
        <PlatformSourceIcon source={rec.source ?? 'meta'} size={18} />
        <span
          className={`rounded px-1.5 py-0.5 text-[10px] ${
            isNativeOnly
              ? 'bg-slate-200/60 text-slate-500 italic'
              : 'bg-slate-100 text-slate-500'
          }`}
        >
          {categoryLabel}
        </span>
      </div>
      <p className="text-xs font-medium leading-snug text-slate-600">{rec.title}</p>
      {rec.estimatedImpact && (
        <p className="mt-0.5 text-[10px] text-slate-400">{rec.estimatedImpact}</p>
      )}
      <p className="mt-1 text-[10px] font-semibold text-[#0891b2]">Open to apply →</p>
  </>
  );

  const rowClass =
    'block border-b border-slate-100 py-2.5 last:border-0 no-underline transition-colors hover:bg-white/80';

  if (external) {
    return (
      <a href={href} target="_blank" rel="noreferrer" className={rowClass}>
        {inner}
      </a>
    );
  }

  return (
    <Link href={href} className={rowClass}>
      {inner}
    </Link>
  );
}

export default function PlatformSpecificPanel({
  recommendations,
  defaultCollapsed = false,
}: PlatformSpecificPanelProps) {
  const [collapsed, setCollapsed] = useState(defaultCollapsed);

  if (recommendations.length === 0) return null;

  const bySource = {
    google: recommendations.filter((r) => r.source === 'google_ads'),
    meta: recommendations.filter((r) => r.source === 'meta'),
  };

  return (
    <div className="mt-6 rounded-xl border border-slate-200/80 bg-slate-50/60">
      <button
        type="button"
        onClick={() => setCollapsed((v) => !v)}
        className="flex w-full items-center justify-between gap-3 px-4 py-3 text-left"
      >
        <div>
          <p className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">
            Platform-specific
          </p>
          <p className="mt-0.5 text-xs text-slate-500">
            Native suggestions from Google Ads &amp; Meta — not generated by MOSAIC
          </p>
        </div>
        <span className="flex shrink-0 items-center gap-2 text-xs text-slate-400">
          {recommendations.length} item{recommendations.length !== 1 ? 's' : ''}
          <span className="text-slate-300">{collapsed ? '▸' : '▾'}</span>
        </span>
      </button>

      {!collapsed && (
        <div className="border-t border-slate-200/60 px-4 pb-3 pt-1">
          {bySource.google.length > 0 && (
            <div className="mb-3 last:mb-0">
              {bySource.meta.length > 0 && (
                <p className="mb-1 pt-2 text-[10px] font-semibold uppercase tracking-wide text-slate-400">
                  {platformSourceLabel('google_ads')}
                </p>
              )}
              {bySource.google.map((rec) => (
                <PlatformRecRow key={rec.id} rec={rec} />
              ))}
            </div>
          )}
          {bySource.meta.length > 0 && (
            <div>
              {bySource.google.length > 0 && (
                <p className="mb-1 pt-2 text-[10px] font-semibold uppercase tracking-wide text-slate-400">
                  {platformSourceLabel('meta')}
                </p>
              )}
              {bySource.meta.map((rec) => (
                <PlatformRecRow key={rec.id} rec={rec} />
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
